### PR TITLE
Creation of an urls file. Renamed an url into bg_seed to differentiate the two.

### PR DESCRIPTION
**Pull request by miniyuuzhan**
Hi, I started using you lib for my blog, I know it maybe wasn't aimed exclusively for Django. But in the django way, I created an urls.py file which allow people to include panavatars url in only line.
This will be usefull if Django views are added to the project.

There is only one thing I'm not sure of, it's the url import in **init**.py, not sure if it's the best way to make panavatar.urls available for import in the users' projects

### CODE REVIEW

**Comment by kvdveer** [comment]
This looks like a very reasonable change to me. I've spotted a few minor issues, which should be easy enough to fix:
- by importing `panavatar.urls` in `panavatar.__init__`, you've made Django a dependency for panavatar. I don't think this is desirable. If you change the include statement to `include("panavatar.urls")`, you don't need to import the urls anywhere else (django will resolve it for you). This way the project remains usable for non-django users. (I use [pelican](http://blog.getpelican.com/) for my blog)
- `bg` and `bg_seed` can really share the same name - the difference is whether a seed is passed in, which is evident from the parameters - no need to repeat that distinction in the url name.
- could you squash the commits, so we don't pollute the change history too much? If you don't know how, don't worry about it - I'll squash it when I merge it.

Otherwise - thanks for contributing!

**Comment by miniyuuzhan** [comment]
It's my first pull request, I'm a long time github user but never contributed, your project is very interesting, I think it's a good way to start.

I think i fixed everything now. I merge my branch develop in master. Because as a habit I coded on develop, but when contributing, I can just work on master.

I never had to squash commit before, and when I looked for it online, I had already pushed.

I saw that there a multiple ways, which one do you use ?

**Comment by kvdveer** [comment]
You've pushed to the master branch, but the merge request is for the develop branch. That's okay though - I'll just pull from the master branch instead.

> I saw that there a multiple ways, which one do you use ?

I'd combine it with the merge: 
- Add your repo as a remote: `git remote add miniyuuzhan https://github.com/miniyuuzhan/python-panavatar.git`
- Download your commite: `git fetch miniyuuzhan`
- Do the actual merge `git merge --squash miniyuuzhan/master`

The downside of this method, is that the commit will apear under my name. In reality I'd use an interactive rebase to combine all your commits into the first one. I wouldn't recommend this route for the novice git-user though: it's a very powerful tool, and it's easy to shoot oneself in the foot with it.

**Comment by miniyuuzhan** [comment]
I merged develop into master. They're in the same state now.

**Comment by miniyuuzhan** [comment]
I just have one request, could you tell me when you update the version that is installed with pip, because for now I rely on an hybrid version of the project. I'd like to use the updated version.

**Comment by kvdveer** [comment]
I've merged your work, and pushed it as version v0.3.3 to pypi (which is what `pip` uses).

Thanks again!

ps. Could you send me a link to your blog when you publish it? I'm really eager to see what people do with this library.

**Pull request closed without merging**
